In [1]:
import pandas as pd

df = pd.read_csv('../data/car_sales_cleaned1.csv')
df

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
0,Male,13500,Ford,Expedition,Auto,Black,26000
1,Male,1480000,Dodge,Durango,Auto,Black,19000
2,Male,1035000,Cadillac,Eldorado,Manual,Red,31500
3,Male,13500,Toyota,Celica,Manual,Pale White,14000
4,Male,1465000,Acura,TL,Auto,Red,24500
...,...,...,...,...,...,...,...
23901,Male,13500,Plymouth,Voyager,Manual,Red,12000
23902,Female,900000,Chevrolet,Prizm,Auto,Black,16000
23903,Male,705000,BMW,328i,Manual,Red,21000
23904,Male,13500,Chevrolet,Metro,Auto,Black,31000
23905,Male,1225000,Lexus,ES300,Auto,Pale White,27500

In [2]:
df = df.drop_duplicates()  # removing duplicates
df.shape

(20358, 7)

In [3]:
df = df.dropna()  # removing rows with missing values
df.shape

(20358, 7)

In [4]:
import joblib
import converter

model = joblib.load('../models/car_gender_model.pkl')
mapper = converter.columns_mapper(['Model', 'Transmission', 'Color'], df)
prediction = model.predict([[mapper['Model']['Escort'], mapper['Transmission']['Auto'], mapper['Color']['Pale White']]])
prediction

Enumerator !!! {'Toyota': 0, 'BMW': 1, 'Opel': 2}
columns_mapper!!! {'Company': {'Toyota': 0, 'Hundai': 1}, 'Model': {'Camry': 0, 'Corolla': 1, 'i10': 2}}
converted!!!             Company  Model
0        0      0
1        0      1
2        1      2

C:\Users\Anna\miniconda3\envs\python-ai\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Male'], dtype=object)

In [6]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import joblib
import converter
model = DecisionTreeClassifier()

mapper = converter.columns_mapper(['Gender','Model', 'Color'], df)
df_converted = converter.convert_x(df, mapper)
X = df_converted[['Color','Gender']]
y = df_converted[['Model']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model.fit(X_train, y_train)
prediction = model.predict(X_test)
score = accuracy_score(y_test, prediction)

print(score)
#joblib.dump(model, '../models/car_predictor_model.pkl')

0.022102161100196464

['../models/car_predictor_model.pkl']

In [15]:
df_hyundai = df[df['Company'] == 'Hyundai']
df_hyundai
# df_hyundai.head()
# len(df_hyundai)

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
16,Female,535000,Hyundai,Accent,Manual,Black,18000
124,Female,1690000,Hyundai,Sonata,Manual,Black,15000
168,Male,955000,Hyundai,Elantra,Manual,Pale White,26000
250,Male,457000,Hyundai,Sonata,Manual,Pale White,21000
289,Male,13500,Hyundai,Sonata,Manual,Black,20000
...,...,...,...,...,...,...,...
23248,Female,1675000,Hyundai,Sonata,Manual,Black,20500
23432,Female,13500,Hyundai,Elantra,Manual,Red,22000
23650,Female,460000,Hyundai,Sonata,Manual,Black,15000
23738,Male,705000,Hyundai,Sonata,Manual,Red,21000
23745,Male,681500,Hyundai,Accent,Manual,Black,18500

In [18]:
df_toyota = df[
    (df['Company'] == 'Toyota') &
    (df['Price ($)'] >= 40000)
]
df_toyota

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
239,Male,1350000,Toyota,Tacoma,Auto,Pale White,53000
258,Male,1151000,Toyota,Corolla,Auto,Pale White,41100
269,Female,825000,Toyota,Tacoma,Manual,Pale White,82000
308,Female,13500,Toyota,Corolla,Auto,Pale White,41000
358,Male,1326000,Toyota,RAV4,Manual,Black,85600
...,...,...,...,...,...,...,...
23379,Male,1300000,Toyota,Celica,Auto,Pale White,45001
23385,Female,615000,Toyota,Tacoma,Auto,Pale White,53000
23443,Male,2400000,Toyota,RAV4,Manual,Black,85000
23476,Male,520000,Toyota,Celica,Auto,Pale White,45000
23735,Male,1635000,Toyota,Tacoma,Auto,Pale White,53501

In [19]:
top_3_models = df['Model'].value_counts().head(3)
print(top_3_models)

Model
Prizm         362
Diamante      347
Silhouette    337
Name: count, dtype: int64

In [20]:
top_3_models = df['Model'].value_counts().head(3).index.tolist()
print(top_3_models)

['Prizm', 'Diamante', 'Silhouette']